### ISSUE TITLE
Question about dev status

### ISSUE THREAD

**Issue by COLABORATI** [stuartkuentzel/angular2-wp-theme#1]
Hi, I just would like to know: is this a one-shot demo or do you plan to work on this on a longer time period? Are you planning on adding features / supporting future wordpress versions /  developing on it?

**Comment by doppiaeast** [comment]
I'm planning on giving it a full update once the final release is out, and will hopefully be rolling out some minor updates before then.

**Comment by COLABORATI** [comment]
cool, keep up the good work, very interesting!
