### ISSUE TITLE
WP Setup

### ISSUE THREAD

**Issue by 3kynox** [stuartkuentzel/angular2-wp-theme#3]
Hello stuartkuentzel,

I was not sure where to post, so I'm asking here.

On tutorial there's no much informations about WordPress setup part, it is just assumed WP have to be installed at start of the tutorial and that we can use WP from another distant server.

Any details on this ?

**Comment by stuartkuentzel** [comment]
Once compiled, you would upload the dist folder, as well as index.php, functions.php and style.css as a theme to wp-content -> themes. You also have to have the WP API 2 plugin installed, so you can query WordPress. 

As for setting up WordPress, it's a bit beyond the scope of this project, but there are lots of good resources out there to get WP up and running either locally or on a server.
