### ISSUE TITLE
'router-outlet' is not a known element

### ISSUE THREAD

**Issue by klihelp** [stuartkuentzel/angular2-wp-theme#4]
Following your tutorial to setup the project, I get the following error:

> 'router-outlet' is not a known element:
> 1. If 'router-outlet' is an Angular component, then verify that it is part of this module.

**Comment by klihelp** [comment]
It's works now.. but not sure what made it work..

1. maybe used the appRoutes constant, instead routes..

`/* app-routing module.ts */

import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { PostListComponent } from './posts/post-list/post-list.component';
const appRoutes: Routes = [
  { `

2. will have a look at this later..

**Comment by yashpalkothari** [comment]
you need to import the routing module and mention in the import section of app.module.ts file
as below:
import {routing}         from './app.routing'

 @NgModule({
  imports:      [ BrowserModule, FormsModule, HttpModule, routing],
  declarations: [ AppComponent] ,
  bootstrap:    [AppComponent] 
})

**Comment by HarisAli94** [comment]
I am still getting an error I have tried everything I can but still routing is not working same error router-outlet is not known

**Comment by kumarvivekgupta** [comment]
I am also having the same error when made a different routing file and wanted t o use child routes there.
